/**
 * Shared catalog for shop + product detail pages.
 */
window.PETSHOP_PRODUCTS = [
  {
    id: 1,
    name: "Premium Dog Food - Chicken & Rice 3kg",
    brand: "SmartHeart",
    price: 2850,
    originalPrice: 3200,
    image: "https://images.unsplash.com/photo-1568640347023-a616a30bc3bd?w=400&h=400&fit=crop",
    category: "Dogs",
    onSale: true,
    sku: "PSH-DOG-CHK-3",
    description:
      "Complete adult dog nutrition with real chicken as the first ingredient and easily digestible rice. Supports healthy skin, a shiny coat, and strong muscles for active dogs of all sizes.",
    highlights: ["Real chicken & rice formula", "Omega fatty acids for coat health", "No poultry by-product meal", "Suitable for adult dogs"],
  },
  {
    id: 2,
    name: "Kitten Dry Food - Ocean Fish 1.5kg",
    brand: "Me-O",
    price: 1450,
    image: "https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=400&h=400&fit=crop",
    category: "Cats",
    sku: "PSH-CAT-KTN-15",
    description:
      "Tailored for growing kittens with high-quality ocean fish protein, DHA for brain development, and calcium for strong bones and teeth.",
    highlights: ["DHA for cognitive development", "Calcium & phosphorus balance", "Crunchy kibble reduces tartar", "For kittens up to 12 months"],
  },
  {
    id: 3,
    name: "Adult Cat Food - Tuna Flavor 3kg",
    brand: "Classic Pets",
    price: 2100,
    originalPrice: 2500,
    image: "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop",
    category: "Cats",
    onSale: true,
    sku: "PSH-CAT-TUN-3",
    description:
      "Irresistible tuna taste that picky cats love, with balanced vitamins and minerals for indoor and outdoor adult cats.",
    highlights: ["Tuna-rich recipe", "Hairball control fibers", "Urinary tract support", "Adult maintenance formula"],
  },
  {
    id: 4,
    name: "Puppy Dry Food - Beef & Vegetable 2kg",
    brand: "SmartHeart",
    price: 1950,
    image: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=400&fit=crop",
    category: "Dogs",
    sku: "PSH-DOG-PUP-2",
    description:
      "Energy-dense puppy formula with beef protein and garden vegetables to fuel growth, play, and a healthy immune system.",
    highlights: ["Small kibble for growing jaws", "Antioxidant blend", "Beef & veg taste", "For puppies up to 12 months"],
  },
  {
    id: 5,
    name: "Tropical Fish Flakes 100g",
    brand: "Trillium",
    price: 650,
    originalPrice: 800,
    image: "https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=400&h=400&fit=crop",
    category: "Fish",
    onSale: true,
    sku: "PSH-FISH-FLK-100",
    description:
      "Color-enhancing flake food for tropical community fish. Floats long enough for fish to feed at the surface without clouding water when used as directed.",
    highlights: ["Multi-vitamin enriched", "Supports vibrant color", "For tetras, barbs & guppies", "Easy daily feeding"],
  },
  {
    id: 6,
    name: "Bird Seed Mix Premium 500g",
    brand: "Canis",
    price: 890,
    image: "https://images.unsplash.com/photo-1452570053594-1b985d6ea890?w=400&h=400&fit=crop",
    category: "Birds",
    sku: "PSH-BRD-MIX-05",
    description:
      "A varied blend of seeds and grains selected for parakeets, cockatiels, and small hookbills. Store in a cool, dry place after opening.",
    highlights: ["Fortified with essential vitamins", "Cleaned & dust-reduced", "Encourages natural foraging", "Resealable-friendly pack"],
  },
  {
    id: 7,
    name: "Rabbit Pellets - Timothy Hay 1kg",
    brand: "Vetzyme",
    price: 1200,
    originalPrice: 1400,
    image: "https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=400&h=400&fit=crop",
    category: "Rabbit",
    onSale: true,
    sku: "PSH-RBT-TIM-1",
    description:
      "High-fiber timothy hay pellets to support healthy digestion and dental wear—ideal as the staple of a rabbit’s daily diet alongside fresh hay and water.",
    highlights: ["High fiber for gut motility", "Timothy hay base", "Dental health support", "Adult rabbits & guinea pigs"],
  },
  {
    id: 8,
    name: "Dog Dental Chew Sticks Pack",
    brand: "SmartHeart",
    price: 750,
    image: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&h=400&fit=crop",
    category: "Dogs",
    sku: "PSH-DOG-CHW-PK",
    description:
      "Chewy sticks designed to reduce plaque buildup through mechanical action while rewarding your dog with a tasty treat during training or quiet time.",
    highlights: ["Helps clean teeth as they chew", "Resealable pack", "Popular with medium breeds", "Use under supervision"],
  },
  {
    id: 9,
    name: "Cat Grooming Brush Set",
    brand: "Classic Pets",
    price: 1100,
    image: "https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?w=400&h=400&fit=crop",
    category: "Cats",
    sku: "PSH-CAT-BRS-SET",
    description:
      "Two-piece grooming set for short- and long-haired cats: detangle gently, remove loose undercoat, and cut down on hairballs around the home.",
    highlights: ["Soft pins & slicker combo", "Comfort-grip handles", "Regular brushing reduces shedding", "Easy to clean"],
  },
  {
    id: 10,
    name: "Aquarium LED Light Bar 60cm",
    brand: "Trillium",
    price: 3500,
    originalPrice: 4200,
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&h=400&fit=crop",
    category: "Fish",
    onSale: true,
    sku: "PSH-FISH-LED-60",
    description:
      "Energy-efficient LED strip for freshwater planted tanks. Provides crisp daylight spectrum to support plant growth and showcase fish colors.",
    highlights: ["60 cm length (check your tank)", "Low heat vs traditional bulbs", "Energy-saving LED", "Sleek aquarium mount"],
  },
  {
    id: 11,
    name: "Premium Dog Shampoo 500ml",
    brand: "Vetzyme",
    price: 980,
    image: "https://www.dogslove.com/en/media/catalog/product/cache/86a2f7b8f8cf4ed32bd6695dfeb9ada3/d/s/dsc06241-960x960.webp",
    category: "Dogs",
    sku: "PSH-DOG-SHP-05",
    description:
      "Mild, pH-balanced shampoo for dogs with sensitive skin. Rinses clean and leaves a fresh scent without stripping natural coat oils.",
    highlights: ["Gentle on sensitive skin", "pH balanced for dogs", "500 ml bottle", "Pair with regular brushing"],
  },
  {
    id: 12,
    name: "Cat Litter - Clumping Clay 5L",
    brand: "Me-O",
    price: 1650,
    originalPrice: 1900,
    image: "https://images.unsplash.com/photo-1511044568932-338cba0ad803?w=400&h=400&fit=crop",
    category: "Cats",
    onSale: true,
    sku: "PSH-CAT-LIT-5",
    description:
      "Fast-clumping bentonite litter that locks in moisture and odor. Forms firm scoops for easier daily maintenance and less waste.",
    highlights: ["Strong clumping action", "Odor control", "5 L bag", "Suitable for covered & open pans"],
  },
];
